name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Configure nginx
        run: |
          echo 'server {
            listen 80;
            root /github/workspace;
            index index.html index.htm;

            location / {
              try_files $uri $uri/ =404;
            }

            location ~* \.(wasm|js)$ {
              add_header Cross-Origin-Opener-Policy "same-origin";
              add_header Cross-Origin-Embedder-Policy "require-corp";
            }
          }' | sudo tee /etc/nginx/conf.d/default.conf

      - name: Build and deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
